#pragma once

// Compile-time check that a board driver actually implements the surface board.h documents.
//
// The problem. The board surface is DUCK-TYPED: `app/harness.cpp` writes `daisyapps::Board board;`
// and calls methods on it, and the only thing that verifies a driver has those methods is a build
// that happens to call them. Because exactly one driver compiles per build (one -DTARGET_*), a
// mistake in `patch_init_board.h` is invisible to a `BOARD=patch` build - and to every other build
// too, until someone selects that target. That is not hypothetical: `patch_init_board.h` carried a
// call to libDaisy's removed C GPIO API (`dsy_gpio_write`) across an API change and nobody noticed,
// because the target had never been compiled.
//
// CI now sweeps all three boards, which catches a driver that stops compiling *its own* code. This
// catches the other half: a driver that compiles fine but no longer satisfies the contract, because
// nothing in that build calls the method that went missing or changed shape. The failure moves from
// "a link error in some other target, later" to "a named static_assert here, now".
//
// One assert per member, on purpose. A single `static_assert(is_board_v<B>)` would report only
// "static assertion failed" and leave the reader to find which of fifteen members is at fault; each
// check below names the method and what it should look like.
//
// HAL-free, so it costs nothing and can be included anywhere. Where a signature mentions a libDaisy
// type (StartAudio's callback), the check is only that the member EXISTS and is unambiguous -
// `decltype(&B::StartAudio)` needs no knowledge of the parameter type. Where the shape carries the
// meaning (Analog returns a float, Poll takes a Controls&), the call is checked properly.

#include <type_traits>
#include <utility>

#include "board/controls.h"

namespace daisyapps {

namespace board_detail {

// Detection idiom. `SPK_BOARD_DETECT(name, expr...)` defines `has_<name><B>`, true iff `expr` is
// well-formed for a `B&` called `b`. Generated by macro for the same reason engine_pads.h does it:
// fifteen hand-written specializations would be fifteen places for a typo to hide.
#define SPK_BOARD_DETECT(name, ...)                                                     \
    template <class B, class = void>                                                    \
    struct has_##name : std::false_type {};                                             \
    template <class B>                                                                  \
    struct has_##name<B, std::void_t<decltype(__VA_ARGS__)>> : std::true_type {};

// --- lifecycle / audio ---------------------------------------------------------------------------
SPK_BOARD_DETECT(init,        std::declval<B&>().Init(0))
SPK_BOARD_DETECT(start_audio, &B::StartAudio)   // callback type is libDaisy's; existence is the check
SPK_BOARD_DETECT(sample_rate, std::declval<B&>().SampleRate())

// --- inputs ---------------------------------------------------------------------------------------
SPK_BOARD_DETECT(analog,      std::declval<B&>().Analog(0))
SPK_BOARD_DETECT(poll,        std::declval<B&>().Poll(std::declval<Controls&>()))
SPK_BOARD_DETECT(start_midi,  std::declval<B&>().StartMidi())

// PollMidi is a member template, so it is checked by CALLING it with a stand-in sink of the exact
// shape the harness passes: a callable taking (status, data1, data2). A driver whose PollMidi takes a
// different sink shape - or is missing - fails here rather than in the one build that uses MIDI.
struct MidiSinkProbe {
    void operator()(uint8_t, uint8_t, uint8_t) const {}
};
SPK_BOARD_DETECT(poll_midi,   std::declval<B&>().PollMidi(std::declval<MidiSinkProbe>()))

// --- outputs ---------------------------------------------------------------------------------------
SPK_BOARD_DETECT(set_indicator, std::declval<B&>().SetIndicator(0, 0.f, 0.f, 0.f))
SPK_BOARD_DETECT(set_user_led,  std::declval<B&>().SetUserLed(true))
SPK_BOARD_DETECT(set_cv_out,    std::declval<B&>().SetCvOut(0, 0.f))
SPK_BOARD_DETECT(set_gate_out,  std::declval<B&>().SetGateOut(true))
SPK_BOARD_DETECT(qspi,          std::declval<B&>().Qspi())

// --- screen facade ----------------------------------------------------------------------------------
// Every board implements all four, as no-ops where there is no display - that is what lets the harness
// call them unconditionally with no #ifdef. A board that omits them because "it has no screen" breaks
// exactly that property, so their absence is an error here even when kHasScreen is false.
SPK_BOARD_DETECT(screen_clear,  std::declval<B&>().ScreenClear())
SPK_BOARD_DETECT(screen_text,   std::declval<B&>().ScreenText(0, 0, "", true))
SPK_BOARD_DETECT(screen_rect,   std::declval<B&>().ScreenRect(0, 0, 1, 1, true))
SPK_BOARD_DETECT(screen_update, std::declval<B&>().ScreenUpdate())

// --- static description ------------------------------------------------------------------------------
// The counts must be usable in a constant expression (the harness sizes arrays and static_asserts from
// them), so each is checked as an integral constant rather than merely as a member that exists.
SPK_BOARD_DETECT(k_analog_count,    std::integral_constant<int, B::kAnalogCount>{})
SPK_BOARD_DETECT(k_button_count,    std::integral_constant<int, B::kButtonCount>{})
SPK_BOARD_DETECT(k_gate_count,      std::integral_constant<int, B::kGateCount>{})
SPK_BOARD_DETECT(k_indicator_count, std::integral_constant<int, B::kIndicatorCount>{})
SPK_BOARD_DETECT(k_cv_out_count,    std::integral_constant<int, B::kCvOutCount>{})
SPK_BOARD_DETECT(k_audio_channels,  std::integral_constant<int, B::kAudioChannels>{})
SPK_BOARD_DETECT(k_has_screen,      std::integral_constant<bool, B::kHasScreen>{})
SPK_BOARD_DETECT(k_screen_width,    std::integral_constant<int, B::kScreenWidth>{})
SPK_BOARD_DETECT(k_screen_height,   std::integral_constant<int, B::kScreenHeight>{})

#undef SPK_BOARD_DETECT

} // namespace board_detail

// Instantiate against a board driver to assert it satisfies the contract. `board.h` does this for
// whichever target was selected; a new driver should be added there and nowhere else.
//
// Usage:  static_assert(check_board_contract<PodBoard>(), "");
// (a function rather than a class so the asserts fire on instantiation with a plain call.)
template <class B>
constexpr bool check_board_contract()
{
    using namespace board_detail;

    static_assert(has_init<B>::value,
                  "board: missing `void Init(int block_size)`");
    static_assert(has_start_audio<B>::value,
                  "board: missing `void StartAudio(daisy::AudioHandle::AudioCallback)` (or it is overloaded)");
    static_assert(has_sample_rate<B>::value,
                  "board: missing `float SampleRate()`");
    static_assert(std::is_same<decltype(std::declval<B&>().SampleRate()), float>::value,
                  "board: SampleRate() must return float");

    static_assert(has_analog<B>::value,
                  "board: missing `float Analog(int i)`");
    static_assert(std::is_same<decltype(std::declval<B&>().Analog(0)), float>::value,
                  "board: Analog(int) must return float (a normalized 0..1 reading)");
    static_assert(has_poll<B>::value,
                  "board: missing `void Poll(Controls&)`");
    static_assert(has_start_midi<B>::value,
                  "board: missing `void StartMidi()` (a no-op where the target has no MIDI input)");
    static_assert(has_poll_midi<B>::value,
                  "board: missing `template <typename Sink> void PollMidi(Sink&&)`, or its sink does "
                  "not accept (uint8_t status, uint8_t data1, uint8_t data2)");

    static_assert(has_set_indicator<B>::value,
                  "board: missing `void SetIndicator(int idx, float r, float g, float b)` "
                  "(a no-op where the target has no LEDs)");
    static_assert(has_set_user_led<B>::value,
                  "board: missing `void SetUserLed(bool)` (every Daisy has the onboard MCU LED)");
    static_assert(has_set_cv_out<B>::value,
                  "board: missing `void SetCvOut(int ch, float norm)` (a no-op where there is no DAC)");
    static_assert(has_set_gate_out<B>::value,
                  "board: missing `void SetGateOut(bool)` (a no-op where there is no gate output)");
    static_assert(has_qspi<B>::value,
                  "board: missing `void* Qspi()` (EngineContext::qspi; edrums persists kit presets there)");
    static_assert(std::is_same<decltype(std::declval<B&>().Qspi()), void*>::value,
                  "board: Qspi() must return void* - the contract stays free of any HAL type");

    static_assert(has_screen_clear<B>::value && has_screen_text<B>::value
                      && has_screen_rect<B>::value && has_screen_update<B>::value,
                  "board: the Screen* facade must be implemented IN FULL - ScreenClear / ScreenText / "
                  "ScreenRect / ScreenUpdate - as no-ops where the target has no display. The harness "
                  "calls them unconditionally; that is what keeps its UI code free of #ifdef");

    static_assert(has_k_analog_count<B>::value && has_k_button_count<B>::value
                      && has_k_gate_count<B>::value && has_k_indicator_count<B>::value
                      && has_k_cv_out_count<B>::value && has_k_audio_channels<B>::value,
                  "board: every control count must be a `static constexpr int` usable in a constant "
                  "expression - kAnalogCount / kButtonCount / kGateCount / kIndicatorCount / "
                  "kCvOutCount / kAudioChannels");
    static_assert(has_k_has_screen<B>::value,
                  "board: missing `static constexpr bool kHasScreen`");
    static_assert(has_k_screen_width<B>::value && has_k_screen_height<B>::value,
                  "board: missing `static constexpr int kScreenWidth` / `kScreenHeight` (0 where the "
                  "target has no display)");

    // Sanity on the values themselves, not just their presence. A count larger than the snapshot it
    // fills would have Poll() write past the end of Controls' arrays.
    static_assert(B::kAnalogCount >= 0 && B::kAnalogCount <= Controls::kMaxAnalog,
                  "board: kAnalogCount exceeds Controls::kMaxAnalog - Poll() would overrun the snapshot");
    static_assert(B::kButtonCount >= 0 && B::kButtonCount <= Controls::kMaxButtons,
                  "board: kButtonCount exceeds Controls::kMaxButtons - Poll() would overrun the snapshot");
    static_assert(B::kGateCount >= 0 && B::kGateCount <= Controls::kMaxGates,
                  "board: kGateCount exceeds Controls::kMaxGates - Poll() would overrun the snapshot");
    static_assert(B::kAudioChannels >= 2,
                  "board: kAudioChannels must be at least 2 - IEngine::process is stereo");
    static_assert(!B::kHasScreen || (B::kScreenWidth > 0 && B::kScreenHeight > 0),
                  "board: kHasScreen is true but the screen has no dimensions");

    return true;
}

} // namespace daisyapps
